from robot_api import move_robot_joints, home_robot, delay_robot, get_robot_joint_angles, control_pneumatic_gripper,get_robot_pose, control_electric_gripper, move_robot_pose,move_robot_cartesian
print("Homing robot...") 
delay_robot(1)
control_electric_gripper(action = "calibrate")
delay_robot(4)
control_electric_gripper(action='move', position=0, speed=150) 
delay_robot(4)
control_electric_gripper(action='move', position=250, speed=150) 
delay_robot(1)
control_electric_gripper(action = "calibrate")
"""
print(get_robot_joint_angles())
print(get_robot_pose())
print("Moving to new position...") 
control_pneumatic_gripper("open",1)
delay_robot(0.2)
control_pneumatic_gripper("close",1)
delay_robot(0.2)
control_pneumatic_gripper("open",1)
delay_robot(0.2)
control_pneumatic_gripper("close",1)
delay_robot(0.2)
control_pneumatic_gripper("open",1)
delay_robot(0.2)
control_pneumatic_gripper("close",1)
delay_robot(0.2)
move_robot_joints([90, -90, 160, 12, 12, 180], duration=5.5)
delay_robot(0.2)
move_robot_joints([50, -60, 180, -12, 32, 0], duration=5.5)
delay_robot(0.2)
move_robot_joints([90, -90, 160, 12, 12, 180], duration=5.5)
delay_robot(0.2)
print(get_robot_pose())
delay_robot(0.2)
move_robot_pose([7, 250, 200, -100, 0, -90], duration=5.5) 
delay_robot(0.2)
move_robot_cartesian([7, 250, 150, -100, 0, -90], duration=5.5) 
"""